version: '3.7'

services:
  react-app:
    build: .
    container_name: react-app
    volumes:
      - .:/app
    networks:
      - app-network
    command: yarn build && yarn start
    expose:
      - "3000"  # Container chạy trên cổng 3000 bên trong mạng Docker

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"  # Chuyển sang cổng 8081 trên máy chủ và chuyển tiếp tới cổng 80 trong container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html  # Đảm bảo thư mục build được ánh xạ đúng
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
