version: '3.7'

services:
  react-app:
    build: .
    container_name: react-app
    volumes:
      - .:/app
    networks:
      - app-network
    command: sh -c "yarn build && yarn start"
    expose:
      - "3000" 

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80" 
    volumes:
      - ./build:/usr/share/nginx/html 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
